---

# base variables
host_purpose: kafka-mg
host_environment: dev
owning_group: mobile

# splunk variables
splunk_rpm_url: "s3://wex-mobile-devops/installers/splunk/splunkforwarder-6.6.3-e21ee54bc796-linux-2.6-x86_64.rpm"

# sumologic variables
sumologic_rpm_url: s3://wex-mobile-devops/installers/sumologic/SumoCollector-19.227-15.x86_64.rpm
sumologic_access_id_param: dev.sumologic.accessid
sumologic_access_key_param: dev.sumologic.accesskey
sumologic_client_name: "kafka-mg-{{host_environment}}"

sumologic_sources:
  bootstrap_source:
    name: bootstrap
    category: "{{owning_group}}/{{ansible_ec2_placement_region}}/{{host_purpose}}/{{host_environment}}/bootstrap"
    pathExpression: "/var/log/bootstrap.log"
  ansible_source:
    name: ansible
    category: "{{owning_group}}/{{ansible_ec2_placement_region}}/{{host_purpose}}/{{host_environment}}/ansible"
    pathExpression: "/var/log/ansible.log"
  kafka_controller:
    name: kafka-controller
    category: "{{owning_group}}/{{ansible_ec2_placement_region}}/{{host_purpose}}/{{host_environment}}/kafka-controller"
    pathExpression: "/var/log/kafka/controller.log"
  kafka-authorizer:
    name: kafka-authorizer
    category: "{{owning_group}}/{{ansible_ec2_placement_region}}/{{host_purpose}}/{{host_environment}}/kafka-authorizer"
    pathExpression: "/var/log/kafka/kafka-authorizer.log"
  kafka-request:
    name: kafka-request
    category: "{{owning_group}}/{{ansible_ec2_placement_region}}/{{host_purpose}}/{{host_environment}}/kafka-request"
    pathExpression: "/var/log/kafka/kafka-request.log"
  kafka-gc:
    name: kafka-gc
    category: "{{owning_group}}/{{ansible_ec2_placement_region}}/{{host_purpose}}/{{host_environment}}/kafka-gc"
    pathExpression: "/var/log/kafka/kafkaServer-gc.log.*.current"
  kafka-server-out:
    name: kafka-server-out
    category: "{{owning_group}}/{{ansible_ec2_placement_region}}/{{host_purpose}}/{{host_environment}}/kafka-server-out"
    pathExpression: "/var/log/kafka/kafkaServer.out"
  kafka-log-cleaner:
    name: kafka-log-cleaner
    category: "{{owning_group}}/{{ansible_ec2_placement_region}}/{{host_purpose}}/{{host_environment}}/kafka-log-cleaner"
    pathExpression: "/var/log/kafka/log-cleaner.log"
  kafka-server:
    name: kafka-server
    category: "{{owning_group}}/{{ansible_ec2_placement_region}}/{{host_purpose}}/{{host_environment}}/kafka-server"
    pathExpression: "/var/log/kafka/server.log"
  kafka-state-change:
    name: kafka-state-change
    category: "{{owning_group}}/{{ansible_ec2_placement_region}}/{{host_purpose}}/{{host_environment}}/kafka-state-change"
    pathExpression: "/var/log/kafka/state-change.log"


# trend micro variables

# jdk variables
jdk_rpm_url: "s3://wex-mobile-devops/installers/jdk/jdk-8u151-linux-x64.rpm"

# kafka variables
zookeeper_package_url: s3://wex-mobile-devops/installers/zookeeper/zookeeper-3.4.10.tar.gz
kafka_package_url: s3://wex-mobile-devops/installers/kafka/kafka_2.11-1.0.0.tgz

kafka_topics:
  transaction-updates:
    replication_factor: 1
    partitions: 1
  transaction-requested:
    replication_factor: 1
    partitions: 1

# route53 variables
route53_zone: "dev.intwexmobile.net"
route53_record: "kafka-mg.dev.intwexmobile.net"
