---

# base variables
owning_group: mwd
devops_bucket: "wex-mobile-devops"

host_platform: nafleet
host_purpose: deuce-service
host_environment: sit

# splunk variables
splunk_mgmt_port: 6089

sumologic_sources:
  cloud_init_source:
    name: cloud-init
    category: "{{owning_group}}/{{host_purpose}}/{{host_environment}}/{{ansible_ec2_placement_region}}/cloud-init"
    pathExpression: "/var/log/cloud-init-output.log"
  bootstrap_source:
    name: bootstrap
    category: "{{owning_group}}/{{host_purpose}}/{{host_environment}}/{{ansible_ec2_placement_region}}/bootstrap"
    pathExpression: "/var/log/bootstrap.log"
  ansible_source:
    name: ansible
    category: "{{owning_group}}/{{host_purpose}}/{{host_environment}}/{{ansible_ec2_placement_region}}/ansible"
    pathExpression: "/var/log/ansible.log"
  catalina_source:
    name: catalina
    category: "{{owning_group}}/{{host_purpose}}/{{host_environment}}/{{ansible_ec2_placement_region}}/catalina"
    pathExpression: "{{tomcat_home}}/logs/catalina.out"
  app_source:
    name: app_source
    category: "{{owning_group}}/{{host_purpose}}/{{host_environment}}/{{ansible_ec2_placement_region}}/app"
    pathExpression: "{{tomcat_home}}/logs/service.log"
  access_source:
    name: access
    category: "{{owning_group}}/{{host_purpose}}/{{host_environment}}/{{ansible_ec2_placement_region}}/access"
    pathExpression: "{{tomcat_home}}/logs/access*.log"

# java version
jdk_rpm_name: jdk1.8

# tomcat config
tomcat_conf_contexts:
  - path: DeuceService/
    jarScan:
      classPath: false
      tld: "jstl-*.jar,spring-webmvc-*.jar,tiles-jsp-*.jar,string-*.jar"
      default: false

tomcat_setenv:
  java_opts: >
    -server
    -Dserver.port={{ tomcat_settings.ports.server }}
    -Dajp.port={{ tomcat_settings.ports.ajp }}
    -Dssl.port={{ tomcat_settings.ports.https }}
    -Dfile.encoding=UTF-8
    -Djava.awt.headless=true
    -Djava.security.egd=file:/dev/./urandom
    -XX:+UseG1GC
    -XX:MaxGCPauseMillis=400
    -XX:G1HeapRegionSize=16m
    -Dfile.encoding=UTF-8
    -Duser.timezone=GMT
    -Djava.util.prefs.PreferencesFactory=com.wex.wol.manager.impl.InMemoryPreferencesManagerImpl
    -Dspring.profiles.active=$APP_ENV
    -Dapp.env=$APP_ENV
  catalina_opts: >
    -Dcom.sun.management.jmxremote
    -Dcom.sun.management.jmxremote.port={{ tomcat_settings.ports.jmx }}
    -Dcom.sun.management.jmxremote.authenticate=false
    -Dcom.sun.management.jmxremote.ssl=false


# dynamic spring properties
spring_props_file: "{{tomcat_home}}/lib/env-service-passwords.properties"
spring_props_properties:
  jdbc-password:
    prop_name: "jdbc.password"
    param_store: "yes"
    encrypted: "yes"
    value: "{{host_environment}}.{{host_purpose}}.jdbc.password"
  db-legacy-password:
    prop_name: "db.legacy.password"
    param_store: "yes"
    encrypted: "yes"
    value: "{{host_environment}}.{{host_purpose}}.db.legacy.password"
  db-wol-password:
    prop_name: "db.wol.password"
    param_store: "yes"
    encrypted: "yes"
    value: "{{host_environment}}.{{host_purpose}}.db.wol.password"
  db-siebel-password:
    prop_name: "db.siebel.password"
    param_store: "yes"
    encrypted: "yes"
    value: "{{host_environment}}.{{host_purpose}}.db.siebel.password"
  db-pram-password:
    prop_name: "db.pram.password"
    param_store: "yes"
    encrypted: "yes"
    value: "{{host_environment}}.{{host_purpose}}.db.pram.password"
  db-ods-password:
    prop_name: "db.ods.password"
    param_store: "yes"
    encrypted: "yes"
    value: "{{host_environment}}.{{host_purpose}}.db.ods.password"
  ldap-password:
    prop_name: "ldap.password"
    param_store: "yes"
    encrypted: "yes"
    value: "{{host_environment}}.{{host_purpose}}.ldap.password"
  siebel-datasource-password:
    prop_name: "siebel.datasource.password"
    param_store: "yes"
    encrypted: "yes"
    value: "{{host_environment}}.{{host_purpose}}.siebel.datasource.password"
  siebel-ftp-password:
    prop_name: "siebel.ftp.password"
    param_store: "yes"
    encrypted: "yes"
    value: "{{host_environment}}.{{host_purpose}}.siebel.ftp.password"
  wex-ftp-password:
    prop_name: "wex.ftp.password"
    param_store: "yes"
    encrypted: "yes"
    value: "{{host_environment}}.{{host_purpose}}.wex.ftp.password"
  salesforce-password:
    prop_name: "salesforce.password"
    param_store: "yes"
    encrypted: "yes"
    value: "{{host_environment}}.{{host_purpose}}.salesforce.password"
