---

- name: DeuceService provision master playbook
  hosts: localhost
  become: yes
  become_user: root
  vars_files:
    - /etc/ansible/variables.yml

  roles:
    - base
    - splunk
    - sumologic
    - trendmicro
    - jdk
    - tomcat
    - dynamic_spring_properties

  post_tasks:
#  Application Download/Property file
    - name: Copy DeuceService Artifact from Artifactory
      maven_artifact:
        group_id: com.wex.fleet.web
        artifact_id: "{{host_purpose}}"
        version: "{{ lookup('env', 'APP_VERSION') | default('latest', true) }}"
        extension: war
        repository_url: 'http://nexus.int.wrightexpress.com/nexus/content/groups/public'
#        repository_url: 'https://us-east-1.artifactory.wexapps.com/artifactory/public'
        dest: "{{tomcat_home}}/webapps/DeuceService.war"
    - name: Copy Basic Properties to Tomcat lib dir
      aws_s3:
        bucket: "{{devops_bucket}}"
        object: "/config/{{host_platform}}/{{host_purpose}}/{{host_environment}}/env-service.properties"
        dest: "{{tomcat_home}}/lib/env-service.properties"
        mode: get
    - name: Copy Customized Properties to Tomcat lib dir
      aws_s3:
        bucket: "{{devops_bucket}}"
        object: "/config/{{host_platform}}/{{host_purpose}}/{{host_environment}}/env-service-customizable.properties"
        dest: "{{tomcat_home}}/lib/env-service-customizable.properties"
        mode: get
    - name: start tomcat
      shell: "{{tomcat_home}}/bin/startup.sh"

# EFS/NFS Mounts
    - name: Create SiebelFS EFS Mount Point
      file:
        path: "{{tomcat_home}}/siebelfs"
        state: directory
        mode: 0755
    - name: Ensure SiebelFS EFS volume is mounted.
      mount:
        name: "{{tomcat_home}}/siebelfs"
        src: "efs-siebelfs.{{host_environment}}-internal.wexfleetservice.com:/"
        fstype: nfs4
        opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
        state: mounted

    - name: Create Reports Data EFS Mount Point
      file:
        path: "{{tomcat_home}}/data"
        state: directory
        mode: 0755
      register: deuce_service_reports_data_dir
    - name: Ensure Reports Data EFS volume is mounted.
      mount:
        name: "{{tomcat_home}}/data"
        src: "efs-reports.{{host_environment}}-internal.wexfleetservice.com:/data"
        fstype: nfs4
        opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
        state: mounted
      register: efs_reports_data_mount

    - name: Create DeuceService Temp EFS Mount Point
      file:
        path: "{{tomcat_home}}/mp_temp"
        state: directory
        mode: 0755
    - name: Ensure DeuceService Temp Data EFS volume is mounted.
      mount:
        name: "{{tomcat_home}}/mp_temp"
        src: "efs-{{host_purpose}}-temp.{{host_environment}}-internal.wexfleetweb.com:/"
        fstype: nfs4
        opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
        state: mounted

# PCI System Reporting
    - name: Generate PCI System Report
      shell: ansible_scripts/ec2/system_report.sh
      args:
        chdir: /root
      register: system_report
      ignore_errors: True
    - name: Export PCI System Report
      when: system_report is succeeded
      aws_s3:
        bucket: "{{devops_bucket}}"
        object: "system-reports/{{host_environment}}/{{system_report.stdout}}"
        src: "/root/{{system_report.stdout}}"
        mode: put
