---

- name: zookeeper kafka provision master playbook
  hosts: localhost
  become: yes
  become_user: root
  vars_files:
    - /etc/ansible/variables.yml

  roles:
    - base
    - splunk
    - trendmicro
    - jdk
    - supervisor
    - zookeeper
    - sumologic
    - cloudwatch_agent
    - cloudwatch_alarms

  post_tasks:
    - name: Update Instance DNS
      route53:
        zone: "{{ zookeeper_dns_domain }}"
        record: "{{ zookeeper_dns_prefix }}-{{ lookup('env', 'ZOOKEEPER_INSTANCE_NUMBER') }}.{{ zookeeper_dns_domain }}"
        ttl: 300
        type: A
        state: present
        value: "{{ ansible_ec2_local_ipv4 }}"
        private_zone: yes
        wait: yes
        overwrite: yes
