---

- name: kafka self-contained provision master playbook
  hosts: localhost
  become: yes
  become_user: root
  vars_files:
    - /etc/ansible/variables.yml

  roles:
    - base
    - chrony
    - supervisor
    - jdk
    - zookeeper
    - kafka
    - sumologic
    - splunk
    - trendmicro
  tasks: []
