---

# base variables
host_purpose: authproxy
host_environment: dev
owning_group: mobile

base_os_limits:
  file_soft_limit:
    domain: "*"
    type: "soft"
    item: "nofile"
    value: "9999"
  file_hard_limit:
    domain: "*"
    type: "hard"
    item: "nofile"
    value: "9999"

# splunk variables
splunk_rpm_url: "s3://wex-mobile-devops/installers/splunk/splunkforwarder-6.6.3-e21ee54bc796-linux-2.6-x86_64.rpm"

# sumologic variables
sumologic_rpm_url: s3://wex-mobile-devops/installers/sumologic/SumoCollector-19.227-15.x86_64.rpm
sumologic_access_id_param: dev.sumologic.accessid
sumologic_access_key_param: dev.sumologic.accesskey
sumologic_client_name: "{{host_purpose}}-{{host_environment}}"

sumologic_sources:
  bootstrap_source:
    name: bootstrap
    category: "{{owning_group}}/{{ansible_ec2_placement_region}}/{{host_purpose}}/{{host_environment}}/bootstrap"
    pathExpression: "/var/log/bootstrap.log"
  ansible_source:
    name: ansible
    category: "{{owning_group}}/{{ansible_ec2_placement_region}}/{{host_purpose}}/{{host_environment}}/ansible"
    pathExpression: "/var/log/ansible.log"
  app_source:
    name: app
    category: "{{owning_group}}/{{ansible_ec2_placement_region}}/{{host_purpose}}/{{host_environment}}/app"
    pathExpression: "/var/log/app.log"

# tendmicro variables

# jdk variables
jdk_rpm_url: "s3://wex-mobile-devops/installers/jdk/jdk-8u151-linux-x64.rpm"

# nexus artifact variables
nexus_artifacts:
  auth-proxy:
    version_env_var: "APP_VERSION"
    group: "com.wex"
    artifact: "auth-proxy"
    downloaded_location: "/root/app.jar"
