---

- name: web-proxy provision master playbook
  hosts: localhost
  become: yes
  become_user: root
  vars_files:
    - /etc/ansible/variables.yml

  roles:
    - base
    - trendmicro
    - sumologic
    - squid