---

- name: kafka broker provision master playbook
  hosts: localhost
  become: yes
  become_user: root
  vars_files:
    - /etc/ansible/variables.yml

  roles:
    - base
    - splunk
    - trendmicro
    - jdk
    - supervisor
    - kafka
    - sumologic
    - cloudwatch_agent
    - cloudwatch_alarms
